#!/bin/bash
export PYTHONPATH=../src:${PYTHONPATH}
export PYTHONPATH=../demo:${PYTHONPATH}
export CBCFLOW_DATA=../data
echo
echo
echo Type: 'run -m unittest discover' in gdb
echo
echo
gdb python
exit $?
