#!/usr/bin/env python
import sys, os, glob, optparse

import cbcflow

def main(args):
    print "TODO: Make a script to show the contents of a case dir."
    casedir, = args
    files = glob.glob(os.path.join(casedir, "*"))
    print files
    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]) or 0)

